### ISSUE TITLE
oxauth client tests effected:  `wait.until` is not working properly after js/selenium updates

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1086]
## Describe the issue
https://github.com/GluuFederation/oxAuth/blob/master/Client/src/test/java/org/gluu/oxauth/BaseTest.java#L414
We got failures due to broken `wait.until` after JS/libs updates. We have to fix `wait.until` condition.

## Expected behavior
Client tests must run successfully

**Comment by yurem** [comment]
Fixed

**Comment by yuriyz** [comment]
still doesn't work in some cases, e.g. https://ox.gluu.org/jenkins/job/oxAuth_4.0_LDAP/1051/testngreports/org.gluu.oxauth.ws.rs/AuthorizationCodeFlowHttpTest/authorizationCodeFlowLoginHint/

**Comment by yuriyz** [comment]
LDAP based build is successful again. All tests are passed https://ox.gluu.org/jenkins/job/oxAuth_4.0_LDAP/1072/.
