### ISSUE TITLE
Logout URI not a JSON Array

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxAuth#202]
This error comes up in 2.4.3 wrapper log while testing against mod_auth_oidc

> INFO   | jvm 1    | 2016/04/15 21:58:50 | 2016-04-15 21:58:50,853 ERROR [xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl] JSONObject["logout_uri"] is not a JSONArray.
INFO   | jvm 1    | 2016/04/15 21:58:50 | org.codehaus.jettison.json.JSONException: JSONObject["logout_uri"] is not a JSONArray.
INFO   | jvm 1    | 2016/04/15 21:58:50 | 	at org.codehaus.jettison.json.JSONObject.getJSONArray(JSONObject.java:440)
INFO   | jvm 1    | 2016/04/15 21:58:50 | 	at org.xdi.oxauth.client.RegisterRequest.fromJson(RegisterRequest.java:1083)
INFO   | jvm 1    | 2016/04/15 21:58:50 | 	at org.xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl.registerClientImpl(RegisterRestWebServiceImpl.java:101)
INFO   | jvm 1    | 2016/04/15 21:58:50 | 	at org.xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl.requestRegister(RegisterRestWebServiceImpl.java:91)

**Comment by yuriyz** [comment]
logout_uri is now array. In 2.4.2 it's literal value but in 2.4.3 it is array, please pass json array.

**Comment by zamilskhan** [comment]
@yuriyz how do I pass JSON array? I am sorry for the noob question. I want to know how to set up the vanilla openID because it seems we need to configure further after installation. We might have to update the docs based on what we have to do after installation to pass JSON Array.

**Comment by yuriyz** [comment]
@zamilskhan lets keep it back-compatible, I will add parsing for both.

**Comment by yuriyz** [comment]
fixed in both version_2.4.3 and master branches.

**Comment by zamilskhan** [comment]
@yuriyz the problem is still there in http://repo.gluu.org/centos/testing/gluu-server-2.4.3-1-1.centos6.x86_64.rpm package.

**Comment by zamilskhan** [comment]
@yuriyz the error is still there in the new package http://repo.gluu.org/centos/testing/gluu-server-2.4.3-1-1.centos6.x86_64.rpm

**Comment by yuriyz** [comment]
@zamilskhan please post full stacktrace from log because I'm not able to reproduce this issue.

**Comment by zamilskhan** [comment]
This shows up when I try to use dynamic registration with mod_auth_oidc.
> INFO   | jvm 1    | 2016/04/19 20:58:33 | 2016-04-19 20:58:33,665 ERROR [xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl] JSONObject["logout_uri"] is not a JSONArray.
INFO   | jvm 1    | 2016/04/19 20:58:33 | org.codehaus.jettison.json.JSONException: JSONObject["logout_uri"] is not a JSONArray.
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.codehaus.jettison.json.JSONObject.getJSONArray(JSONObject.java:440)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.xdi.oxauth.client.RegisterRequest.fromJson(RegisterRequest.java:1083)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl.registerClientImpl(RegisterRestWebServiceImpl.java:101)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl.requestRegister(RegisterRestWebServiceImpl.java:91)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.resteasy.ResteasyContextInjectionInterceptor.aroundInvoke(ResteasyContextInjectionInterceptor.java:59)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:77)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:185)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:103)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.xdi.oxauth.register.ws.rs.RegisterRestWebServiceImpl_$$_javassist_seam_41.requestRegister(RegisterRestWebServiceImpl_$$_javassist_seam_41.java)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.resteasy.ResteasyResourceAdapter$1.process(ResteasyResourceAdapter.java:145)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.resteasy.ResteasyResourceAdapter.getResource(ResteasyResourceAdapter.java:120)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamResourceServlet.service(SeamResourceServlet.java:80)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
INFO   | jvm 1    | 2016/04/19 20:58:33 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/04/19 20:59:32 | 2016-04-19 20:59:32,886 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - <Reloading registered services.>

**Comment by yuriyz** [comment]
@zamilskhan you are eithr testing on wrong version or fix somehow is not in that version. In RegisterRequest line 1083 from stacktrace you've provided there are no executable line.

https://github.com/GluuFederation/oxAuth/blob/version_2.4.3/Client/src/main/java/org/xdi/oxauth/client/RegisterRequest.java#L1083

**Comment by yuriyz** [comment]
@yurem is fix really included in the version that @zamilskhan  is testing ?

**Comment by zamilskhan** [comment]
@yuriyz I downloaded this [oxatuh war](https://ox.gluu.org/maven/org/xdi/oxauth-server/2.4.3.Final/oxauth-server-2.4.3.Final.war) and replaced in `/opt/tomcat/webapps` and it worked.
